name: Update Blog Posts

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '*/1 * * * *'
  pull_request:
    branches:
      - main

jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
  
      - name: Install dependencies
        run: |
          pip install feedparser gitpython

      - name: Configure Git
        run: |
          git config --global user.name 'bsjin1122'
          git config --global user.email 'kitty7579@hanmail.net'

      - name: Run script
        run: python scripts/update_velog.py
      
      - name: Check for Changes
        run: |
          git status
          git diff
        id: check_changes

      - name: Commit and Push Changes
        # 변경 사항이 있는 경우에만 실행
        if: steps.check_changes.outputs.changed_files != ''
        run: |
          git checkout -b update-blog-posts-branch
          git add .
          git commit -m "Velog posts 업데이트"
          git push https://${{ secrets.GH_PAT }}@github.com/bsjin1122/velog.git update-blog-posts-branch
      
      - name: Create Pull Request
        # 변경 사항이 있는 경우에만 실행
        if: steps.check_changes.outputs.changed_files != '' 
        uses: thomaseizinger/create-pull-request@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          head: update-blog-posts-branch
          base: main
          title: "PR 자동 생성"
