name: Update Blog Posts

on:
  push:
    branches:
      - update-blog-posts-branch
  # schedule:
  #   - cron: '*/1 * * * *'
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write


jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
  
      - name: Install dependencies
        run: |
          pip install feedparser gitpython

      - name: Configure Git
        run: |
          git config --global user.name 'bsjin1122'
          git config --global user.email 'kitty7579@hanmail.net'

      - name: Run script
        run: python scripts/update_velog.py
      
      - name: Check for Changes
        run: |
          git status
          git diff
        id: check_changes

      - name: Commit and Push Changes
        # 변경 사항이 있는 경우에만 실행
        run: |
          git add .
          git commit --allow-empty -m "Velog posts 업데이트함"
          git push https://${{ secrets.GH_PAT }}@github.com/bsjin1122/velog.git update-blog-posts-branch
     
          
      - name: pull-request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Velog 게시글 업로드 PR"
          pr_body: |
            :crown: *An automated PR*

      - name: auto-approval
        if: github.actor == 'github-actions[bot]'  
        uses: hmarr/auto-approve-action@v4
        with:
          pull-request-number: ${{ github.event.inputs.pullRequestNumber }}
          review-message: "Auto approved automated PR Test"


      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     commit-message: "Velog posts 업데이트"
      #     branch: update-blog-posts-branch  # PR 생성 시 사용될 브랜치 이름
      #     title: "PR 자동 생성"
      #     base: main
      
