name: Update Blog Posts
  

on:
  push:
      branches:
        - main  # 또는 워크플로우를 트리거하고 싶은 브랜치 이름
  schedule:
    - cron: '*/1 * * * *' # 5분마다 update

jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install feedparser gitpython

    - name: Run script
      id: update_velog  # Step ID 추가
      run: python scripts/update_velog.py
    
    - name: Push changes
      if: success()
      run: |
        git config --local user.name 'bsjin1122'
        git config --local user.email 'kitty7579@hanmail.net'
        git add .
        COMMIT_MESSAGE=$(cat "${{ steps.update_velog.outputs.commit_message }}")
        git commit -m "$COMMIT_MESSAGE"
        git push https://${{ secrets.GH_PAT }}@github.com/bsjin1122/velog.git
      env:
        COMMIT_MESSAGE: ${{ steps.update_velog.outputs.commit_message }}