name: Update Blog Posts

on:
  push:
    branches:
      - update-blog-posts-branch
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: 
    inputs: 
      pullRequestNumber:
        description: Pull request number to auto-approve
        required: false
        
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write


jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
  
      - name: Install dependencies
        run: |
          pip install feedparser gitpython

      - name: Configure Git
        run: |
          git config --global user.name 'bsjin1122'
          git config --global user.email 'kitty7579@hanmail.net'

      - name: Run script
        run: python scripts/update_velog.py
      
      - name: Check for Changes # Git 상태 확인
        run: |
          git status
          git diff
        id: check_changes
      
        # Current branch is: refs/heads/update-blog-posts-branch
      - name: Display Current Branch
        run: |
          echo "Current branch is: $GITHUB_REF"

      - name: Set Date Format for PR Title
        run: echo "PR_DATE=$(date '+%y%m%d')" >> $GITHUB_ENV
          
      # 변경사항이 있는 경우에만 실행
      # - name: Create Pull Request
      #   uses: diillson/auto-pull-request@v1.0.1
      #   with:
      #     destination_branch: "main"
      #     github_token: ${{ secrets.VELOG_TOKEN }}
      #     pr_label: "velog"
      #     pr_title: "[${{ env.PR_DATE }}]  Velog 게시글 업로드"
      #     pr_allow_empty: false
      #     pr_body: |
      #       :satisfied: [Velog 새 게시글 확인하기](https://velog.io/@greendev/posts)
      #   id: create_pr  

      - name: Create Pull Request (peter-evans)
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.VELOG_TOKEN }}
          author: bsjin1122 <kitty7579@hanmail.net>
          body: | 
            :satisfied: [Velog 새 게시글 확인하기](https://velog.io/@greendev/posts)
          labels: velog
          title: "[${{ env.PR_DATE }}]  Velog 게시글 업로드"
          branch: main
          base: update-blog-posts-branch
          assignees: bsjin1122
        id: create_pr


      - name: Display PR Number # 날짜 형식
        run: |
          echo "Pull Request Number: ${{ steps.create_pr.outputs.pull-request-number }}" 
      
      - name: PR Auto Merge 
        # PR이 있는 경우에만 실행  
        if: steps.create_pr.outputs.pull-request-number != ''  
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.VELOG_TOKEN }}
          pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
          # merge-method:
      
    
      ########### 시도 했던 방법들 -- 사용 가능한 스크립트들입니다.

      # 방법1. PR 자동 승인
      # - name: PR auto approval
      #   uses: tgymnich/fork-sync@v2.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     owner: bsjin1122
      #     base: main
      #     head: update-blog-posts-branch
      #     pr_message: "velog 작성 - PR approve 완료"

      # 방법2. PR 자동 승인
      # - name: PR 자동 승인
      #   uses: hmarr/auto-approve-action@v4
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     pull-request-number: ${{ steps.create_pr.outputs.pr_number }}
      #     review-message: "Auto approved automated PR Test"

      # 방법3. PR 자동 생성 
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     commit-message: "Velog posts 업데이트"
      #     branch: update-blog-posts-branch  # PR 생성 시 사용될 브랜치 이름
      #     title: "PR 자동 생성"
      #     base: main
      
      # 방법4. PR 자동 승인
      - name: PR 자동 승인
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.VELOG_TOKEN }}
          pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
          review-message: "Auto approved automated PR"
             

